export * from './Hero'
export * from './About'
export * from './Services'
export * from './Portfolio'
export * from './Pricing'
export * from './WhyChooseUs'
export * from './Contact'
export * from './Faq'
